Rails.application.config.assets.precompile += %w( admin/users/sessions.css )
Rails.application.config.assets.precompile += %w( admin/users.css )
Rails.application.config.assets.precompile += %w( admin/publications.css )
Rails.application.config.assets.precompile += %w( admin/dashboards.css )
Rails.application.config.assets.precompile += %w( ie-spacer.gif )
Rails.application.config.assets.precompile += %w( gritter.png )
Rails.application.config.assets.precompile += %w( gritter-close.png )