development:
  adapter: mysql2
  encoding: utf8
  database: safira_development
  username: root
  password:
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: safira_test
  username: root
  password:
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: safira
  username: root
  password:
