# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 294e7e6941e68804aaa1e567a903c704820523ffa7c727db5b1c12f10b00b88a9dbd3ef0acb95adec21c61b878c8446367e8a14d9dc48a93870c036ad08af2bc

test:
  secret_key_base: aa7ea1e754c2ca6f9b6631416d755de86c5711fcf0da010214b7d76969f4459154fd79dc9132e794e8659b8cb227a465850c58d5b65419dc3c8473bd1d02c9f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
